Fixed conjob
porowns/pathfinder-docker pull request #13
Opened 2019-12-28 21:54 UTC by november781

Cron needed its logging directory made in the image (decided to add that to the Dockerfile and let it be in the image instead of doing it in the entrypoint script)

The default_cronjob needed to have sudo so it could make a local php call instead of root

Since it looks like the static database still needs to be imported, I added the .zip and instructions for it

2019-12-29 07:15 UTC, porowns commented on README.md
> +3. [Import static databse.](#Importing-static-databse)
typo here

2019-12-29 17:16 UTC, november781 reviewed
Fixed typos

2019-12-29 20:00 UTC, porowns requested changes

2019-12-29 20:00 UTC, porowns commented on README.md
> +1. Download the static database.
Should just specify command: `wget https://github.com/exodus4d/pathfinder/raw/master/export/sql/eve_universe.sql.zip`

2019-12-29 20:00 UTC, porowns commented on README.md
> +2. Unzip `eve_universe.sql.zip`.
Should add command: `unzip eve_universe.sql.zip`

2019-12-29 20:00 UTC, porowns commented on README.md
> +4. Enter the db container `docer-compose exec db /bin/bash`.
Typo here... `docker-compose exec db /bin/bash`

2019-12-29 20:00 UTC, porowns commented on README.md
> +3. Copy the databse into the db container `docker cp eve_universe.sql {full container name: eg. pathfinder-docker_db_1}:/eve_universe.sql`.
Typo here... `database`

2019-12-29 20:00 UTC, porowns commented on README.md
> +5. Make sure you have completed step 2 in Setup.
This line isn't needed imo, they're following steps

2019-12-29 20:00 UTC, porowns commented on README.md
> +6. Link static databse `mysql -u root -p eve_universe< eve_universe.sql`.
Typo

2019-12-29 20:16 UTC, november781 reviewed
added those commands as requested

2019-12-29 20:31 UTC, november781 commented
all changes should be up-to-date and ready for merge

2019-12-30 18:30 UTC, porowns approved these changes

2019-12-30 18:31 UTC, merged